<?php
namespace Mce\Date;

require_once dirname( __FILE__ ) . '/../../../../lib/Mce/Date/Range.php';

use \DateTime,
    \DateInterval;

/**
 * Test class for RangeInclusive.
 * Generated by PHPUnit on 2012-05-16 at 19:03:06.
 */
class RangeTest extends \PHPUnit_Framework_TestCase {

    protected $range;
    protected $start;
    protected $end;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp () {
        $this->start = new DateTime();
        $this->start->setTime( 0, 0, 0 );

        $this->end = clone $this->start;
        $this->end->setTime( 23, 59, 59 );

        $this->range = new Range( $this->start, $this->end );

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown () {
        unset( $this->range );
        unset( $this->dateOutOfRange );
        unset( $this->dateInRange );
    }
    
    /**
     * @covers Mce\Date\Range::__construct
     */
    public function testThrowsInvalidArgumentExceptionWhenStartIsAfterEnd() {
        $this->setExpectedException( "InvalidArgumentException" );
        new Range( $this->end, $this->start );
    }

    /**
     * @covers Mce\Date\Range::getStart
     */
    public function testGetStart () {
        $this->assertTrue( $this->range->getStart() === $this->start);
    }

    /**
     * @covers Mce\Date\Range::getEnd
     */
    public function testGetEnd () {
        $this->assertTrue( $this->range->getEnd() === $this->end);
    }

}
?>
